js-beautify support for mustache and handlebars
google/vim-codefmt pull request #170
Opened 2021-03-27 14:23 UTC by abgeana

The mustache/vim-mustache-handlebars plugin sets the filetype to either
html.handlebars or html.mustache. Even though js-beautify supports
formatting for these files, the `--type` parameter must be `html`.

This commit sets the `--type` parameter to `html` when the filetype
matches the regex `html\..*`.

2021-03-27 14:35 UTC, abgeana commented
@googlebot I signed it!

2021-03-27 14:56 UTC, abgeana commented
CI is still failing, but I see in the tests for js-beautify are fine this time. The problem is with another formatter I think.

2021-03-27 18:40 UTC, dbarnett commented
> CI is still failing, but I see in the tests for js-beautify are fine this time. The problem is with another formatter I think.

Interesting, looks like #167 and for some reason Travis never ran on that. I'll look into it.

2021-03-27 18:41 UTC, dbarnett requested changes

2021-03-27 18:41 UTC, dbarnett commented on autoload/codefmt/jsbeautify.vim
>          \ &filetype is# 'javascript'
This loose matching includes some patterns you might not have intended. Consider changing it to something like
```vim
&filetype is# 'html' || &filetype =~# '\mhtml\.'
```

Without the `#` the behavior subtly depends on the `'ignorecase'` setting, and the loose `.*` will match on characters that aren't a literal dot, such as some weird `htmlos` filetype vim has that doesn't seem to be anything like actual HTML syntax.

2021-03-27 18:41 UTC, dbarnett commented on autoload/codefmt/jsbeautify.vim
> +    elseif &filetype
Was this line here by accident? It's "harmless" but has no effect.

2021-03-28 09:59 UTC, abgeana commented
I addressed the two changes you requested and also squashed the commits to make history nicer. Let me know if this works.

2021-03-28 18:45 UTC, dbarnett commented
Thanks, merging!

2021-03-28 18:45 UTC, dbarnett approved these changes

2021-03-28 18:45 UTC, merged